schemas/calorimetric.json, schemas/hygrothermal.json, schemas/optical.json, schemas/photovoltaic.json
=> Remove detailed descriptions of data as this is done in the corresponding `*Data.json` schema

CHANGELOG.md, apis/database.graphql
=> Correct minor errors in database API

CHANGELOG.md, apis/database.graphql, queries/database/allData.graphql, queries/database/data.graphql
See the individual commit messages for details.
=> Make minor changes

CHANGELOG.md, examples/dbe/optical/nearnormalHemisphericalSolarReflectanceAccordingToStandard.json, examples/dbe/origin/methodAccordingToStandard.json, examples/dbe/origin/originMethodAccordingToStandard.json, schemas/common.json, tests/valid/common/standard.json
=> Use acronyms for standardizers as identifiers

CHANGELOG.md, Makefile, package-lock.json, package.json, schemas/building.json, schemas/calorimetric.json, schemas/calorimetricData.json, schemas/common.json, schemas/component.json, schemas/dbe.json, schemas/dsb.json, schemas/gaps.json, schemas/geometry.json, schemas/hygrothermal.json, schemas/hygrothermalData.json, schemas/identifier.json, schemas/layer.json, schemas/material.json, schemas/method.json, schemas/number.json, schemas/optical.json, schemas/opticalData.json, schemas/photovoltaic.json, schemas/photovoltaicData.json, schemas/stakeholder.json, schemas/string.json, schemas/unit.json
=> Use JSON Schema Draft 2019-09 and upgrade tooling

CHANGELOG.md, schemas/building.json, schemas/calorimetric.json, schemas/calorimetricData.json, schemas/common.json, schemas/component.json, schemas/dbe.json, schemas/dsb.json, schemas/gaps.json, schemas/geometry.json, schemas/hygrothermal.json, schemas/hygrothermalData.json, schemas/identifier.json, schemas/layer.json, schemas/material.json, schemas/method.json, schemas/number.json, schemas/optical.json, schemas/opticalData.json, schemas/photovoltaic.json, schemas/photovoltaicData.json, schemas/stakeholder.json, schemas/string.json, schemas/unit.json
See the comment https://github.com/ise621/building-envelope-data/issues/187#issuecomment-788779203 for reasons.
=> Add version to JSON Schemas

examples/dbe/generalComponents/16mmArgon.json, examples/dbe/generalComponents/materialArgon.json, examples/dbe/photovoltaic/bipvInverterBuildingNatIse.json, examples/dbe/photovoltaic/bipvModuleBuildingNatIse.json, examples/dbe/photovoltaic/bipvModuleSunovation.json, examples/dbe/photovoltaic/bipvModuleSunovationEnamel.json, examples/dbe/photovoltaic/bipvModuleSunovationGlazingLayer.json, examples/dbe/photovoltaic/bipvModuleSunovationGlazingUnit.json, examples/dbe/photovoltaic/bipvModuleSunovationLayer.json, examples/dbe/photovoltaic/bipvModuleSunovationUnit.json, schemas/component.json, schemas/photovoltaicData.json
=> Create a second BIPV module example based on Sunovation data

CHANGELOG.md, tests/valid/method/methodThreePhase.json
=> Fix three phase method test

examples/dbe/calorimetric/bistMeasurement.json
Move "characteristics" from "calorimetric" to "component".
=> Repair the calorimetric example bistMeasurement.json

examples/dbe/allDomains/semitransparentBuildingIntegratedPhotovoltaicThermal.json, examples/dbe/optical/es-sda-example0101layer.json, examples/dbe/optical/es-sda-example0102unit.json, examples/dbe/photovoltaic/photovoltaicWithOptical.json, tests/valid/opticalData/polarization/equallySandPpolarized.json, tests/valid/opticalData/polarization/polarizationUnknown.json
Update the examples and tests which where modified during the work on
pull request #195 so that they reflect the new definition of the
uncertainty of numbers of #195.
=> Update the new examples and tests

CONTRIBUTING.md, README.md
To explain the relationship between the three repositories and to define
the process of collaborating with forks of all three repositories.
Closes #208
=> Add metabase and database to README and CONTRIBUTING

schemas/common.json, schemas/component.json, schemas/photovoltaicData.json
I extended the description and corrected a typo.
=> Improve description of `CIELAB`

examples/dbe/optical/ColourRenderingIndexCIELAB.json, tests/valid/opticalData/mirroredValues/infraredEmittance.json, tests/valid/opticalData/mirroredValues/nearnormalHemisphericalSolarReflectance.json, tests/valid/opticalData/mirroredValues/nearnormalHemisphericalSolarTransmittance.json, tests/valid/opticalData/mirroredValues/nearnormalHemisphericalVisibleReflectance.json
and one example. It shall be possible to query these values with GraphQL in the future. Relates to #233
=> Illustrate the values to be mirrored by tests

schemas/number.json, schemas/opticalData.json, tests/invalid/opticalData/negativeAzimuth.json, tests/invalid/opticalData/polarAngleOutOfRange.json
The polar angle must be between 0° and 90° and the azimuth angle must
be between 0° and 360°. I added invalid tests for this.
Closes #242
=> Limit the range of `polar` and `azimuth`

examples/dbe/generalComponents/16mmArgon.json, examples/dbe/koester.json, examples/dbe/photovoltaic/bipvModuleSunovationEnamel.json, examples/dbe/photovoltaic/bipvModuleSunovationGlazingLayer.json, examples/dbe/photovoltaic/bipvModuleSunovationGlazingUnit.json, examples/dbe/photovoltaic/bipvModuleSunovationLayer.json, examples/dbe/photovoltaic/bipvModuleSunovationUnit.json, examples/dbe/photovoltaic/photovoltaicWithOptical.json
so that they can be presented.
=> Improve the examples

.graphql-schema-linterrc, apis/metabase.graphql
Added the latest metabase GraphQL schema with some breaking changes, in particular, HotChocolate changed the default casing of scalar types whose names are acronyms --- I preferred the old casing.
Closes #263
=> Update metabase GraphQL schema

schemas/opticalData.json
I have included the spelling corrections of #122. Closes #265. It would have been better to solve the conflicts in #122 than to include them manually in this pull request.
=> Include spelling corrections of #122

CONTRIBUTING.md, README.md
Improve the documentation of the repository so that it is harmonized with the documentation of the [metabase](https://github.com/ise621/metabase) and the [database](https://github.com/ise621/database).
=> Update of CONTRIBUTING und README

CHANGELOG.md, CONTRIBUTING.md, README.md, package.json
Closes #276 
Make sure to change your clones by running in the respective directories
```
git remote set-url origin git@github.com:building-envelope-data/api.git
git remote set-url origin git@github.com:building-envelope-data/machine.git
git remote set-url origin git@github.com:building-envelope-data/metabase.git
git remote set-url origin git@github.com:building-envelope-data/database.git
```
=> Rename organization to `building-envelope-data` and API repository to `api`

CHANGELOG.md, apis/metabase.graphql, queries/metabase/tutorial.graphql
=> Update GraphqL schema of metabase to match the current deployed version

.github/workflows/draft-new-release.yml
Remove superfluous step that was necessary in metabase project from which I copied these actions.
=> Fix release actions

CHANGELOG.md, Dockerfile, package-lock.json, package.json
=> Upgrade development packages

CHANGELOG.md, Makefile, package-lock.json, schemas/building.json, schemas/calorimetric.json, schemas/calorimetricData.json, schemas/common.json, schemas/component.json, schemas/dbe.json, schemas/dsb.json, schemas/gaps.json, schemas/geometry.json, schemas/hygrothermal.json, schemas/hygrothermalData.json, schemas/identifier.json, schemas/layer.json, schemas/material.json, schemas/method.json, schemas/number.json, schemas/optical.json, schemas/opticalData.json, schemas/photovoltaic.json, schemas/photovoltaicData.json, schemas/stakeholder.json, schemas/string.json, schemas/unit.json
=> Upgrade json schema to draft 2020-12

queries/database/tutorial.graphql, queries/metabase/tutorial.graphql
We need more example queries which can be entered for example at https://igsdb-icon.herokuapp.com/icon_graphql/ and https://www.solarbuildingenvelopes.com/graphql/ .
=> Create tutorial queries for database

.prettierrc, Makefile, apis/metabase.graphql
=> Configure prettier explicitly

Dockerfile, apis/database.graphql, schemas/component.json
Currently https://github.com/building-envelope-data/api/blob/48fca7aef7cf813d4a63b7a8497409448fff6406/apis/database.graphql#L1506-L1794 is partly outdated.
Resolves https://github.com/building-envelope-data/api/issues/203
See also https://github.com/building-envelope-data/database/issues/2 and https://github.com/building-envelope-data/api/issues/187
=> Improve and fix approvals
